export const rouletteCoffees = [
  {
    id: 1,
    name: "Ethiopian Yirgacheffe",
    origin: "Ethiopia · Single Origin",
    roast: "Light",
    milk: "None",
    strength: "Double",
    temperature: "Hot",
    syrup: "None",
    tastingNotes: ["Citrus", "Floral", "Tea-like"],
    aroma: "Smells like a sunrise and a lemon orchard",
    originStory: "From the misty highlands of southern Ethiopia, birthplace of coffee itself. Yirgacheffe beans are hand-sorted and sun-dried, producing a cup that's more fruit bowl than coffee mug.",
    universeReason: "The stars aligned for something bright and unexpected today. Also, you've been too predictable lately — time to shake things up with a little citrus energy.",
    cupColor: "#D4A96A",
    hasFoam: false
  },
  {
    id: 2,
    name: "Double Espresso",
    origin: "Italy · Classic Blend",
    roast: "Dark",
    milk: "None",
    strength: "Triple",
    temperature: "Hot",
    syrup: "None",
    tastingNotes: ["Bold", "Low Acid", "High Caffeine"],
    aroma: "Deep, rich, and completely unapologetic",
    originStory: "The original Italian formula — a precise 25ml shot pulled at 9 bars of pressure. No filters, no frills. Just pure concentrated coffee essence in a tiny cup that means business.",
    universeReason: "The universe sees you have things to do and zero time for nonsense. Clarity incoming.",
    cupColor: "#2C1A0E",
    hasFoam: false
  },
  {
    id: 3,
    name: "Lavender Oat Latte",
    origin: "Pacific Northwest · Craft",
    roast: "Light",
    milk: "Oat",
    strength: "Single",
    temperature: "Hot",
    syrup: "Vanilla",
    tastingNotes: ["Floral", "Creamy", "Calming"],
    aroma: "Like a lavender field decided to become a coffee shop",
    originStory: "Born in the craft cafés of Portland, this drink married the calming properties of lavender with the natural sweetness of oat milk. It's less coffee, more self-care ritual.",
    universeReason: "Your nervous system sent a distress signal. The universe intercepted it and prescribed lavender. You're welcome.",
    cupColor: "#C8B8D4",
    hasFoam: true
  },
  {
    id: 4,
    name: "Caramel Macchiato",
    origin: "Seattle · Iconic",
    roast: "Medium",
    milk: "Dairy",
    strength: "Double",
    temperature: "Hot",
    syrup: "Caramel",
    tastingNotes: ["Sweet", "Buttery", "Smooth"],
    aroma: "That exact coffee smell you dream about, but better",
    originStory: "Literally means 'marked with caramel' in Italian. The layered pour — milk first, espresso through the foam, caramel drizzle on top — creates a drink that looks as good as it tastes.",
    universeReason: "Classic for a reason. The universe knows you needed comfort today, not adventure. It picked right.",
    cupColor: "#8B5E3C",
    hasFoam: true
  },
  {
    id: 5,
    name: "Cold Brew Vanilla",
    origin: "New York · Cold Craft",
    roast: "Medium",
    milk: "Oat",
    strength: "Double",
    temperature: "Iced",
    syrup: "Vanilla",
    tastingNotes: ["Smooth", "Sweet", "Low Bitterness"],
    aroma: "Cool, vanilla-kissed, dangerously easy to drink",
    originStory: "Cold brew is never rushed — steeped for 18 hours in cold water, extracting all the sweetness and none of the bitterness. Add vanilla oat and you've got New York café culture in a cup.",
    universeReason: "The universe clocked your energy level — somewhere between 'functioning adult' and 'needs a nap.' Cold brew vanilla is the exact middle ground.",
    cupColor: "#6B4C35",
    hasFoam: false
  },
  {
    id: 6,
    name: "Matcha Espresso Fusion",
    origin: "Japan × Italy · Fusion",
    roast: "Medium",
    milk: "Almond",
    strength: "Single",
    temperature: "Iced",
    syrup: "None",
    tastingNotes: ["Earthy", "Grassy", "Balanced"],
    aroma: "A zen garden with an espresso bar in the corner",
    originStory: "A collision of two ancient rituals — Japanese matcha ceremony meets Italian espresso culture. The earthy bitterness of matcha balances the sweetness of almond milk, creating something genuinely new.",
    universeReason: "Two great things that shouldn't work together but absolutely do. The universe is feeling experimental today, and so should you.",
    cupColor: "#7A9E6E",
    hasFoam: false
  },
  {
    id: 7,
    name: "Obsidian Latte",
    origin: "Colombia · Dark Roast",
    roast: "Extra Dark",
    milk: "Dairy",
    strength: "Triple",
    temperature: "Hot",
    syrup: "None",
    tastingNotes: ["Intense", "Smoky", "Full Body"],
    aroma: "Walks into the room before you do",
    originStory: "Colombian extra-dark beans roasted to the edge of their comfort zone, producing a brew so bold it needs no introduction. Triple shot, full dairy — this is coffee that doesn't apologise for itself.",
    universeReason: "Mercury is in retrograde, which apparently means you need something bold and unapologetic. Also it's statistically the most satisfying coffee on a stressful day.",
    cupColor: "#1A0A04",
    hasFoam: true
  },
  {
    id: 8,
    name: "Hazelnut Drift",
    origin: "Brazil · Medium Roast",
    roast: "Medium",
    milk: "Almond",
    strength: "Double",
    temperature: "Hot",
    syrup: "Hazelnut",
    tastingNotes: ["Nutty", "Caramel", "Smooth"],
    aroma: "Like a hazelnut tree decided to open a café",
    originStory: "Brazilian beans have a natural nuttiness that pairs perfectly with hazelnut syrup and almond milk. The result tastes like it was engineered for maximum comfort — because it basically was.",
    universeReason: "The universe sensed you needed something familiar but slightly elevated. Like your usual order, but wearing a better jacket.",
    cupColor: "#7B5C3E",
    hasFoam: true
  },
  {
    id: 9,
    name: "Citrus Bloom",
    origin: "Kenya · Single Origin",
    roast: "Light",
    milk: "None",
    strength: "Double",
    temperature: "Iced",
    syrup: "None",
    tastingNotes: ["Bright", "Citrus", "Crisp"],
    aroma: "Like squeezing a lemon over a really good espresso",
    originStory: "Kenyan AA beans are grown at 6,000+ feet elevation, producing an almost wine-like acidity and a brilliant citrus brightness. Served iced, it's like lemonade went to coffee school.",
    universeReason: "The universe is trying to wake you up gently. Not with a shout — with a zing. Bright, crisp, and kind of electric.",
    cupColor: "#C4A35A",
    hasFoam: false
  },
  {
    id: 10,
    name: "Velvet Macchiato",
    origin: "Italy · Classic",
    roast: "Medium",
    milk: "Dairy",
    strength: "Double",
    temperature: "Hot",
    syrup: "None",
    tastingNotes: ["Chocolate", "Creamy", "Balanced"],
    aroma: "That exact coffee smell you dream about",
    originStory: "The macchiato's name means 'stained' — espresso stained with just enough steamed milk to soften the blow. It's the coffee world's perfect compromise between power and grace.",
    universeReason: "Balanced. Composed. A little bit of everything done right. The universe thinks you deserve something that just works, no drama.",
    cupColor: "#7D5A3C",
    hasFoam: true
  },
  {
    id: 11,
    name: "Dark Oat Storm",
    origin: "Sumatra · Bold",
    roast: "Dark",
    milk: "Oat",
    strength: "Triple",
    temperature: "Hot",
    syrup: "None",
    tastingNotes: ["Smoky", "Earthy", "Bold"],
    aroma: "Deep forest vibes with a coffee shop at the centre",
    originStory: "Sumatran beans are wet-hulled during processing, creating an earthy, full-bodied profile unlike anywhere else on earth. Triple shot, oat milk — for those who want plant-based but refuse to sacrifice intensity.",
    universeReason: "Big energy was required today. The universe obliged. This one hits like a plot twist.",
    cupColor: "#3D2314",
    hasFoam: true
  },
  {
    id: 12,
    name: "Sunrise Almond Mist",
    origin: "Guatemala · Light Roast",
    roast: "Light",
    milk: "Almond",
    strength: "Single",
    temperature: "Hot",
    syrup: "Vanilla",
    tastingNotes: ["Delicate", "Floral", "Nutty"],
    aroma: "Smells like a slow morning with nowhere to be",
    originStory: "Guatemalan Antigua beans grown in volcanic soil produce a remarkably clean, delicate cup. With almond milk and a touch of vanilla, this is coffee as meditation — slow, gentle, intentional.",
    universeReason: "The universe decided you needed a moment, not a meeting. Soft landing incoming.",
    cupColor: "#D4B896",
    hasFoam: true
  }
];

export const getRandomCoffee = (excludeId?: number) => {
  const filtered = excludeId ? rouletteCoffees.filter(c => c.id !== excludeId) : rouletteCoffees;
  const randomIndex = Math.floor(Math.random() * filtered.length);
  return filtered[randomIndex];
};
